#!/bin/bash

SPARK_HOME=$HOME/spark/current
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

echo "Loading spark env"
export PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$JAVA_HOME/bin:$PATH
export SPARK_HOME
export JAVA_HOME
